/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ctdp_rfdynhud_editor_input_DirectInputConnection */

#ifndef _Included_net_ctdp_rfdynhud_editor_input_DirectInputConnection
#define _Included_net_ctdp_rfdynhud_editor_input_DirectInputConnection

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_ctdp_rfdynhud_editor_input_DirectInputConnection
 * Method:    nativeInitInputDeviceManager
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_net_ctdp_rfdynhud_editor_input_DirectInputConnection_nativeInitInputDeviceManager
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     net_ctdp_rfdynhud_editor_input_DirectInputConnection
 * Method:    initDirectInputAndStartPolling
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_net_ctdp_rfdynhud_editor_input_DirectInputConnection_initDirectInputAndStartPolling
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     net_ctdp_rfdynhud_editor_input_DirectInputConnection
 * Method:    nativeInterruptPolling
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_ctdp_rfdynhud_editor_input_DirectInputConnection_nativeInterruptPolling
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif
